Added Form Component and Test
ucsb-cs156-f23/proj-courses-f23-7pm-3 pull request #32
Opened 2023-11-28 05:18 UTC by ivan512az

In this PR, Mariana and I added the corresponding EnrollmentCode and Quarter table to the CourseDetailsTable.

The image on Storybook:
<img width="1084" alt="Screenshot 2023-11-27 at 9 16 29 PM" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/assets/103396645/c3437057-6867-4ce7-bcf2-afed51decf79">

Closes #14

2023-11-28 19:02 UTC, pconrad commented on frontend/src/fixtures/courseDetailsFixtures.js
> +      enrollmentCode: "ABC123",
Can we make the enrollment code fixtures match the format of actual enrollment codes?  Those are 5 digit numbers.
```suggestion
      enrollmentCode: "12345",
```

2023-11-28 19:03 UTC, pconrad commented on frontend/src/tests/components/CourseDetailsTable.test.js/CourseDetailsTable.test.js
> +    ).toHaveTextContent("CDF456");
```suggestion
    ).toHaveTextContent("23456");
```

2023-11-28 19:07 UTC, pconrad requested changes
I'm having trouble reviewing this because there is no context about what problem this solves for the end user.   The issue that this closes is no help either; it looks like this:

<img width="755" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/assets/1119017/fc57e663-75ef-436a-b203-26885f95929b">


@KateUnger you wrote this issue.  What larger epic or story is this a part of?  We have that we are adding two fields to a form, but what page is that form being used on ?

Where does this fit in?   When we create or modify a component, we need to understand where that component is going to be used, and I don't see any connection between this form and a proposed usage.  Further, the issue talked about a "form" but this is a table.

Please consult with one another, and clarify both the issue and the PR.  We don't merge code for it's own sake, but only if it's connected to meeting a user need.

2023-11-28 22:05 UTC, ivan512az commented
@pconrad Fixed enrollment code to only numbers as stated. Additionally, I fixed the kanban instructions to reflect on the work from this PR.

2023-11-29 23:28 UTC, pconrad approved these changes
LGTM

2023-11-29 23:29 UTC, merged

2023-11-29 23:53 UTC, ThatsBadJuju approved these changes