Added Course Dropdown Menu for Personal Schedules
ucsb-cs156-f23/proj-courses-f23-7pm-3 pull request #40
Opened 2023-11-29 02:27 UTC by ThatsBadJuju

Closes #6 

In this PR, I built a dropdown menu for personal schedules when you add a course to a schedule.

To do this, log in and go to Personal Schedules -> Add Schedule. Create a new schedule, and then go to Add Course. Add a course to your schedule with an enrollment code like this for example:

<img width="661" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/assets/22358471/7db35226-4a9d-4abb-9d4e-b4a33a8be6e8">

This should generate a new course like this:
<img width="1390" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/assets/22358471/8f5071d7-da8f-4ac8-9df8-e24a30fcde34">

**DOKKU LINK:** https://proj-courses-thatsbadjuju.dokku-11.cs.ucsb.edu/ 

Lastly, there's a known bug on both the original (main branch) and modified personal schedules page where deleting the schedule doesn't delete its associated courses, which are then stuck there until you wipe the database. This can be fixed in a different issue/PR.

2023-11-29 23:40 UTC, pconrad commented on frontend/src/main/components/Courses/CourseForm.js
>    // Stryker disable all
The `// Stryker disable all` here should be paired with `// Stryker restore all` otherwise mutation testing is turned off for this entire file.

2023-11-29 23:43 UTC, pconrad requested changes
So there are a few suggesitons below.

In addition, there are known bugs here: I found that I was unable to use the form when there was only one option in the form (i.e. when I had created only one personal schedule.)  

So this still needs some work, but since we are up against the deadline, I'm ok to merge it even though it's imperfect and then make issues to try to fix the bugs.

2023-11-30 00:11 UTC, ThatsBadJuju commented
I think I have a solution to the bug you just described; I'm making a new test right now to get my fix to pass mutation / coverage tests.

2023-11-30 00:27 UTC, ThatsBadJuju commented
Also, I couldn't find a way to test the lack of schedules in my course page tests when it gets mutated, so I left it out of stryker mutation testing for now.

2023-11-30 00:34 UTC, mucucsb approved these changes
LGTM

2023-11-30 01:08 UTC, pconrad requested changes
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-30 01:19 UTC, ThatsBadJuju commented
I can't get the test to cover the case where there are no local schedules - I'll keep working on it for a little bit more, but if not I'll push as-is.

2023-11-30 01:21 UTC, ThatsBadJuju commented
This in particular:

<img width="430" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/assets/22358471/d1d6891d-7297-4dff-a852-74046c364a7a">

No matter how I modify the tests, schedule is never a null value

2023-11-30 02:11 UTC, ThatsBadJuju commented
@pconrad I partially fixed the first course schedule bug we talked about, but there are still some bugs that I noted in issue #43 - deleting a schedule makes adding courses fail until another schedule is created.

2023-11-30 02:27 UTC, pconrad approved these changes
LGTM

2023-11-30 02:29 UTC, rosillo-m approved these changes
LGTM

2023-11-30 06:47 UTC, merged